name: .NET WASM

on:
  push:
    branches: [ "*" ]
  
jobs:
  build:

    runs-on: ubuntu-latest  
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Install WASM
      run: dotnet workload install wasm-tools
      
    - name: Build
      run: dotnet publish -c Release
        

    
